# Change these first
owner: pfaocle # Your GitHub username
repo: beor-upptime # Your Github repository name

# Add your sites here
sites:
  - name: Son of Bëor
    url: https://beor.pfaocle.co.uk
  - name: pfaocle.co.uk
    url: https://pfaocle.co.uk

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /beor-upptime
  logoUrl: https://beor.pfaocle.co.uk/assets/img/logo.svg
  name: Son of Bëor Upptime
  introTitle: "**Upptime** for Son of Bëor."
  introMessage: Son of Bëor status page using **real-time** data from our [Github repository](https://github.com/pfaocle/beor-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
